### ISSUE TITLE
Use Heredoc for the css strings.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/github_labels#4]
As per http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc

PR coming up...

**Comment by bugfolder** [comment]
We have several pages on docs.b.org devoted to coding standards:

https://docs.backdropcms.org/documentation/coding-and-documentation-standards

The word "heredoc" doesn't appear on any of them (in fact, not anywhere on docs.backdropcms.org).

There is specific language about quotes (single versus double): https://docs.backdropcms.org/php-standards#quotes

Perhaps we should update our coding standards to specify when to use Heredoc, then start using it?

The coding standards do recommend using single quotes over double quotes, because it's faster. Heredoc behaves just like double quotes. Would single quotes still be preferable?

**Comment by klonos** [comment]
You know what? ...you're absolutely right! I most likely have confused things in my head 😅 

Let's close this, and we can revisit if we decide to handle things that way.
